### ISSUE TITLE
ModuleNotFoundError: No module named 'pyensembl.biotypes'

### ISSUE THREAD

**Issue by aravindprasad** [ctokheim/deepDegron#3]
I installed from source using the conda method and the install works without any errors
```bash
$ git clone https://github.com/ctokheim/deepDegron
$ cd deepDegron
$ conda env create -f environment.yml  # install dependencies
$ conda activate deepDegron  # activate environment
$ pyensembl install --release 75 --species human  # download human hg19 reference data
$ pyensembl install --release 95 --species human  # download human hg38 reference data
$ python setup.py install  # install deepDegron
```
So far so good. But when you run the example from the tutorial in the [documentation](https://deepdegron.readthedocs.io/en/latest/tutorial.html), I get the following error

Command: 
```bash
$ deepdegron score -i tests/data/gata3_mutations.txt -c models/cterm/neural_network_pos_specific.pickle,models/cterm/neural_network_bag_of_amino_acids.pickle -o GATA3_delta_degron_potential.txt
```
Error: 
```bash
Traceback (most recent call last):
  File "/opt/conda/envs/deepDegron/bin/deepdegron", line 33, in <module>
    sys.exit(load_entry_point('deepDegron==1.1.0', 'console_scripts', 'deepdegron')())
  File "/opt/conda/envs/deepDegron/lib/python3.7/site-packages/deepDegron-1.1.0-py3.7.egg/deepDegron/deep_degron.py", line 170, in cli_main
    main(opts)
  File "/opt/conda/envs/deepDegron/lib/python3.7/site-packages/deepDegron-1.1.0-py3.7.egg/deepDegron/deep_degron.py", line 154, in main
    import deepDegron.score_mutations as score
  File "/opt/conda/envs/deepDegron/lib/python3.7/site-packages/deepDegron-1.1.0-py3.7.egg/deepDegron/score_mutations.py", line 18, in <module>
    import varcode
  File "/opt/conda/envs/deepDegron/lib/python3.7/site-packages/varcode/__init__.py", line 16, in <module>
    from .variant import Variant
  File "/opt/conda/envs/deepDegron/lib/python3.7/site-packages/varcode/variant.py", line 31, in <module>
    from pyensembl.biotypes import is_coding_biotype
ModuleNotFoundError: No module named 'pyensembl.biotypes'
```

**Comment by aravindprasad** [comment]
**Cause:**
setuptools>=58 breaks support for use_2to3, a method from the PyVCF module. So pip ends up installing an older version of PyVCF (v0.4.3 instead of v0.6.8). This in turn installs an older version of varcode (v0.3.18 instead of v1.0.3). This older version of varcode does not have the classes used by deepDegron which causes the missing module error while running the example.

**Fix:**
add the following line to environment.yml
```bash
- setuptools<58
```
The final environment.yml looks like this
```bash
name: deepDegron
channels:
- bioconda
- defaults
dependencies:
- pip
- setuptools<58
- numpy=1.16.5
- scipy
- nose
- pandas
- scikit-learn
- tensorflow=1.14.0
- keras
- pip:
  - pyensembl
  - varcode
```

**Comment by ctokheim** [comment]
Thank you for investigating the issue. I've now update the repository with your suggested change for the setuptools version.
